# Start from fresh debian stretch & add some tools
# note: rsyslog & curl (openssl,etc) needed as dependencies too
FROM debian:bullseye
RUN apt update
RUN apt install -y rsyslog nano curl

# Download BI Connector to /mongosqld
WORKDIR /tmp
RUN curl https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-x86_64-debian92-v2.14.0.tgz -o bi-connector.tgz && \
    tar -xvzf bi-connector.tgz && rm bi-connector.tgz && \
    mv /tmp/mongodb-bi-linux-x86_64-debian92-v2.14.0 /mongosqld

# Setup default environment variables
ENV MONGODB_HOST mongodb
ENV MONGODB_PORT 27017
ENV LISTEN_PORT 3307
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD pass
ENV sslPEMKeyFile 'C:\opt\certs\mdb.pem'
# Start Everything
# note: we need to use sh -c "command" to make rsyslog running as deamon too
RUN service rsyslog start
CMD sh -c "/mongosqld/bin/mongosqld --mongo-uri mongodb://$MONGODB_HOST:$MONGODB_PORT/?connect=direct --addr 0.0.0.0:$LISTEN_PORT --sslMode requireSSL --sslPEMKeyFile 'C:\opt\certs\mdb.pem' --sslCAFile 'C:\opt\certs\mdbca.crt' --auth -u admin -p pass"
rsa -in bi.key -out unencrypt_bi.key
rsa -in mdbprivate.key -check -noout
x509 -in mdbca.crt -noout -pubkey 
pkeyutl -encrypt -in test.txt -pubin -inkey mdbca.pub.crt -out cipher.txt 
copy .\mdbprivate.key + .\mdbca.crt mdbca.pem
x509 -in mdbca.crt -out mycert.pem -outform PEM
openssl x509 -in bi.crt -text -noout
openssl x509 -in mdbca.crt -text -noout
openssl rsa -in bi.key -check



